### ISSUE TITLE
not all trait items implemented, missing: `sol_type_name`

### ISSUE THREAD

**Issue by abdullah-almesbahi** [shuhuiluo/uniswap-v3-sdk-rs#35] opened 2024-02-19 19:15 UTC
I just added `uniswap-v3-sdk = { version = "0.23.2", features = ["extensions"] }` to my Cargo.toml and then cargo build and I got the following error

```
/ sol! {
178 | |     interface IQuoterV2 {
179 | |         function quoteExactInput(bytes memory path, uint256 amountIn)
180 | |             external
...   |
255 | |
256 | |         struct ExactOutputSingleParams {
    | |______________________________________^ missing `sol_type_name` in implementation
    |
    = note: this error originates in the macro `sol` (in Nightly builds, run with -Z macro-backtrace for more info)
    = help: implement the missing item: `fn sol_type_name() -> Cow<'static, str> { todo!() }`
    ```

**Comment by abdullah-almesbahi** [comment] 2024-02-19 21:24
this is my cargo file.  hope it will help you to replicate

```
[package]
name = "mev_bot"
version = "0.1.0"
edition = "2021"


[dependencies]
revm = "5.0.0"
bytes = "1.2.1"
rand = "0.8.5"
dotenv = "0.15.0"
hashbrown = "0.14.0"
tokio = { version = "1.29.0", features = ["full"] }
tokio-stream = { version = "0.1", features = ['sync'] }
log = "0.4.17"
url = "2.3.1"
dashmap = "5.4.0"
hex = "0.4.3"
serde = "1.0.145"
serde_json = "1.0"
anyhow = "1.0.71"
reqwest = "0.11.12"
thiserror = "1.0.37"
futures = "0.3.5"
itertools = "0.11.0"

# EVM based crates
cfmms = "0.6.2"
ethers-providers = "2.0"
ethers-core = "2.0"
ethers-contract = { version = "2.0", default-features = false }
ethers = { version = "2.0", features = ["abigen", "ws", "rustls"] }
uniswap-v3-sdk = { version = "0.23.2", features = ["extensions"] }

# logging
indoc = "2"
fern = { version = "0.6.2", features = ["colored"] }
chrono = "0.4.23"
colored = "2.0.0"
csv = "1.2.2"
indicatif = "0.17.5"
```

**Comment by shuhuiluo** [comment] 2024-02-19 22:15
The errors seems related to [alloy-sol-types](https://crates.io/crates/alloy-sol-types). And uniswap-v3-sdk seems to be the only crate using it.

I don't know what the issue is. Try
```sh
rustup update
cargo clean
cargo check
```

Closing this issue since I can't control downstream dependency conflicts.

**Closed** 2024-02-23 08:47 UTC
